
services:
  web: 
    environment:
      spring_profiles_active: docker
    build: .
    ports:
      - 8080:8080
  db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: fhirdb
